# Generated by Django 6.0.2 on 2026-03-04 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_descriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescription',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='role',
            field=models.CharField(choices=[('BACKEND', 'Backend Developer'), ('FRONTEND', 'Frontend Developer'), ('FULLSTACK', 'Fullstack Developer'), ('DATA', 'Data Scientist'), ('DEVOPS', 'DevOps Engineer'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='parsed_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
