# Generated by Django 6.0.2 on 2026-03-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_descriptions', '0002_remove_jobdescription_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
