# Generated by Django 6.0.2 on 2026-03-05 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_descriptions', '0003_jobdescription_company_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('HR', 'HR'), ('Technical', 'Technical'), ('Mixed', 'Mixed')], max_length=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='created', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_descriptions.jobdescription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('communication_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('relevance_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('problem_solving_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ai_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rule_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('final_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feedback', models.TextField()),
                ('scoring_version', models.CharField(default='v1.0', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interviews.interviewsession')),
            ],
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_token', models.IntegerField()),
                ('output_token', models.IntegerField()),
                ('total_token', models.IntegerField()),
                ('cost_estimate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interviews.interviewsession')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(choices=[('AI', 'AI'), ('Candidate', 'Candidate')], max_length=20)),
                ('message_text', models.TextField()),
                ('message_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.interviewsession')),
            ],
        ),
    ]
