# Generated by Django 6.0.2 on 2026-03-08 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_interviewreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestion',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transcriptmessage',
            name='message_order',
            field=models.PositiveIntegerField(),
        ),
    ]
